title: Project Aura | Powerdreams Tech
description: Edge AI & Precision Agriculture for Avocado Farming in Juja, Kenya.
theme: jekyll-theme-minimal

# Navigation (Appears at the top of your page)
header_pages:
  - index.md
  - hardware.md
  - orchard_health.md

# Brand Links
github:
  is_project_page: true
  repository_url: https://github.com/martinmati131-svg/Project--aura-